### ISSUE TITLE
Can not Run the code

### ISSUE THREAD

**Issue by akshatjai258** [rpaudel42/ds_dd#1]
I am getting this error message on running.

Traceback (most recent call last):
  File "main.py", line 51, in <module>
    main()
  File "main.py", line 12, in main
    available_dataset = ds.get_available_dataset()
  File "C:\Users\aksha\Desktop\dsdd\ds_dd\graph\dataset.py", line 312, in get_available_dataset
    available_dataset.append(self.initialize_dataset(d)) #d[0], d[1], d[2], d[3], d[4]))
  File "C:\Users\aksha\Desktop\dsdd\ds_dd\graph\dataset.py", line 291, in initialize_dataset
    g_list = self.read_send_gfile(d[3])
  File "C:\Users\aksha\Desktop\dsdd\ds_dd\graph\dataset.py", line 174, in read_send_gfile
    with open(fileName) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/DBLP.g'

**Comment by akshatjai258** [comment]
Actually the problem was gbad/bin/gbad was not in correct format. I replsced it with latest gbad binary file now its solved
